# app/config/routing.yml
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
ausentismo:
    resource: "@AusentismoBundle/Controller/"
    type:     annotation
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /usuario

expediente_backend_expediente:
    resource: "@ExpedienteBundle/Resources/config/routing/expediente.yml"
    prefix:   /intranet/expediente

expediente:
    resource: "@ExpedienteBundle/Controller/"
    type:     annotation
    prefix:   /

documento:
    resource: "@DocumentoBundle/Controller/"
    type:     annotation
    prefix:   /
