
ausentismo:
    resource: "@AusentismoBundle/Controller/"
    type:     annotation
    prefix:   /

usuario:
    resource: "@UsuarioBundle/Controller/"
    type:     annotation
    prefix:   /usuario

expediente_backend_expediente:
    resource: "@ExpedienteBundle/Resources/config/routing/expediente.yml"
    prefix:   /extranet/expediente

expediente:
    resource: "@ExpedienteBundle/Controller/"
    type:     annotation
    prefix:   /

documento:
    resource: "@DocumentoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
