<?php

namespace Siarme\DocumentoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DocMedicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocMedicoRepository extends EntityRepository
{
}
