<?php

namespace Siarme\DocumentoBundle\Repository;

/**
 * TurnoCitacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoCitacionRepository extends \Doctrine\ORM\EntityRepository
{
}
