<?php

namespace Siarme\AusentismoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AgenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgenteRepository extends EntityRepository
{
}
