<?php

namespace Siarme\ExpedienteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TipoTramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTramiteRepository extends EntityRepository
{
}
