<?php

namespace Siarme\ExpedienteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TramiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TramiteRepository extends EntityRepository
{


      /**
     * Encuentra el ultimo tramite del expediente indicado
     *
     * 
     */
	public function findUltimo($expediente)
	{

        $em = $this->getEntityManager();

        $consulta = $em->createQuery(
        			   'SELECT t
                        FROM ExpedienteBundle:Tramite t JOIN t.expediente e
                        WHERE e.id= :id AND t.estado= :estado
                        ORDER BY t.id DESC
                        ');
        $consulta->setParameter('id', $expediente->getId());
        $consulta->setParameter('estado', false);  
        $consulta->getMaxResults(1);
        $tramite = $consulta->getResult();            
                 
        return $tramite[0];
    }
}
